name: Update lists

on:
  schedule:
  - cron: '15,45 * * * *' # Run every hour at 15 and 45 minutes past the hour
  workflow_dispatch:

jobs:
  update-lists:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 1
    - name: Set up Python 3.
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: 3.13

    - name: Install uv
      uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

    - run: uv sync --frozen
    - name: Generate list files
      env:
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: |
        mkdir newlists
        uv run python update-lists.py --output-dir newlists
    - name: Commit files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-branches origin lists
        git fetch --depth 1 origin lists
        git switch lists
        cp -rf newlists/* lists/ && rm -rf newlists
        git add lists
        git commit -m "Automatically updated lists: $(date)" -a || true
    - name: Push changes
      run: |
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git push -u github lists

    - name: notify-slack-failed
      uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
      if: failure()
      env:
        message: ":x:Adblock lists update job failed.\\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        errors: true
        payload: |
          {
            "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
            "text": "${{ env.message }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ env.message }}"
                }
              }
            ]
          }